- name: deploy docker dev server
  hosts: web01
  become: yes

  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker 

    
    - name: return latest commit head id
      command: cd skillhanger && git rev-parse --short HEAD
      register: DOCKER_TAG       

    - name: Pull default Docker image
      docker_image:
        name: "ozunuane/skillhanger:{{DOCKER_TAG}}"
        source: pull

    - name: Create default containers
      docker_container:
        name: "skillhangerweb01"
        image: "ozunuane/skillhanger:{{DOCKER_TAG}}"
        state: started
        ports:
          - "8080:8081"
    

#   - name: start docker container
#      docker_container:
#        name: skillhanger
#        image: "ozunuane:skillhanger:{{DOCKER_TAG}}"
#        ports:
#          - "8080:8080"
            


